[
    {
        name: "Ocean View Apartment",
        type: "apartement",
        description: "A beautiful apartment with a stunning ocean view.",
        numberOfRooms: 3,
        floor: 5,
        country: "USA",
        city: "Los Angeles",
        address: "123 Ocean Drive",
        postalCode: "90001",
        price: 1500.0,
        img: "ocean_view.jpg",
        owner_id: 1,
    },
    {
        name: "Mountain Retreat",
        type: "villa",
        description:
            "A secluded villa in the mountains, perfect for a getaway.",
        numberOfRooms: 4,
        floor: 1,
        country: "Switzerland",
        city: "Zermatt",
        address: "456 Mountain Road",
        postalCode: "3920",
        price: 2500.0,
        img: "mountain_retreat.jpg",
        owner_id: 2,
    },
    {
        name: "City Center House",
        type: "house",
        description: "A spacious house located in the heart of the city.",
        numberOfRooms: 5,
        floor: 2,
        country: "Canada",
        city: "Toronto",
        address: "789 City Center Blvd",
        postalCode: "M5J 2N8",
        price: 3000.0,
        img: "city_center_house.jpg",
        owner_id: 3,
    },
];
